version: '3.4'

services:
  database:
    image: postgres
    container_name: ${DATABASE_SUBDOMAIN_NAME:-database}-db
    restart: always
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - db-data:/var/lib/postgres
    environment:
      # So you don't have to use root, but you can if you like
      POSTGRES_PASSWORD: ${USER_PASSWORD:-password}
      # You can use whatever password you like
      POSTGRES_USER: ${USER_NAME:-user}
    networks:
      - proxy
    expose:
      # Opens port 3306 on the container
      - 5432
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${DATABASE_SUBDOMAIN_NAME:-database}-secure.entrypoints=postgres"
      - "traefik.http.routers.${DATABASE_SUBDOMAIN_NAME:-database}-secure.rule=Host(`${DATABASE_SUBDOMAIN_NAME:-database}.${HOST:-localhost}`)"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${DATABASE_SUBDOMAIN_NAME:-database}-pgadmin
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pgadmin-${DATABASE_SUBDOMAIN_NAME:-database}-secure.entrypoints=websecure"
      - "traefik.http.routers.pgadmin-${DATABASE_SUBDOMAIN_NAME:-database}-secure.rule=Host(`pgadmin.${HOST:-localhost}`)"
    environment:
      PGADMIN_HOST: ${DATABASE_SUBDOMAIN_NAME:-database}-db

networks:
  proxy:
    external: true

volumes:
  db-data:
    name: ${DATABASE_SUBDOMAIN_NAME:-database}-db
